# Generated by Django 2.1.3 on 2018-11-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20181117_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='hire_data',
            new_name='hire_date',
        ),
    ]
